/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPartidasRouteImport } from './routes/_app.partidas'
import { Route as AppNuevaPartidaRouteImport } from './routes/_app.nueva-partida'
import { Route as AppPartidaGameIdRouteImport } from './routes/_app.partida.$gameId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPartidasRoute = AppPartidasRouteImport.update({
  id: '/partidas',
  path: '/partidas',
  getParentRoute: () => AppRoute,
} as any)
const AppNuevaPartidaRoute = AppNuevaPartidaRouteImport.update({
  id: '/nueva-partida',
  path: '/nueva-partida',
  getParentRoute: () => AppRoute,
} as any)
const AppPartidaGameIdRoute = AppPartidaGameIdRouteImport.update({
  id: '/partida/$gameId',
  path: '/partida/$gameId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nueva-partida': typeof AppNuevaPartidaRoute
  '/partidas': typeof AppPartidasRoute
  '/partida/$gameId': typeof AppPartidaGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nueva-partida': typeof AppNuevaPartidaRoute
  '/partidas': typeof AppPartidasRoute
  '/partida/$gameId': typeof AppPartidaGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/nueva-partida': typeof AppNuevaPartidaRoute
  '/_app/partidas': typeof AppPartidasRoute
  '/_app/partida/$gameId': typeof AppPartidaGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/nueva-partida' | '/partidas' | '/partida/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/nueva-partida' | '/partidas' | '/partida/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/nueva-partida'
    | '/_app/partidas'
    | '/_app/partida/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/partidas': {
      id: '/_app/partidas'
      path: '/partidas'
      fullPath: '/partidas'
      preLoaderRoute: typeof AppPartidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nueva-partida': {
      id: '/_app/nueva-partida'
      path: '/nueva-partida'
      fullPath: '/nueva-partida'
      preLoaderRoute: typeof AppNuevaPartidaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partida/$gameId': {
      id: '/_app/partida/$gameId'
      path: '/partida/$gameId'
      fullPath: '/partida/$gameId'
      preLoaderRoute: typeof AppPartidaGameIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNuevaPartidaRoute: typeof AppNuevaPartidaRoute
  AppPartidasRoute: typeof AppPartidasRoute
  AppPartidaGameIdRoute: typeof AppPartidaGameIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNuevaPartidaRoute: AppNuevaPartidaRoute,
  AppPartidasRoute: AppPartidasRoute,
  AppPartidaGameIdRoute: AppPartidaGameIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
